version: 2
jobs:
  build:
    docker:
      - image: docker:latest

    working_directory: ~/build
    steps:
      - checkout
      - setup_remote_docker
      
      - run:
          name: build-image
          command: docker build -t opuscapita/ci-node8:latest .
          
      - run:
          name: deploy-image
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push opuscapita/ci-node8:latest
